Spec flow вербальные тесты
AV-Household/svc-achievements pull request #1
Opened 2023-01-27 16:16 UTC by DonAbaddon

Составлены вербальные тесты с использованием SpecFlow

2023-01-27 16:19 UTC, DonAbaddon commented
### Сервис для подсчета достижений

Сервис должен реализовывать следующие варианты использования:

* настройка правил подсчета рейтинга от выполнения задач
* настройка правил подсчета рейтинга от полученных оценок
* подсчет рейтинга с учетом
  * выполнения задач
  * полученных оценок
  * штрафов
  * бонусов
* вывод информации о подсчитанном рейтинге

2023-01-29 11:20 UTC, avmorozov requested changes
В целом хорошо
В репозитории лишние файлы

2023-01-29 11:20 UTC, avmorozov commented on Achievements/Achievements.Specs/ImplicitUsings.cs
> +global using NUnit;
Файлы из bin и obj не кладутся в репозиторий

2023-01-29 11:20 UTC, avmorozov commented on Achievements/Achievements.Specs/Features/ViewRating.feature
> +
И не сообщает рейтинг дочери:

2023-01-29 11:20 UTC, avmorozov commented on Achievements/Achievements.Specs/Achievements.Specs.csproj
> +    <PackageReference Include="SpecFlow.NUnit" Version="3.9.40" />
Перейти на XUnit

2023-01-29 11:20 UTC, avmorozov commented on Achievements/Achievements.Specs/Features/SetUpGradeRules.feature
> +
Опечатка

2023-02-02 13:22 UTC, closed without merging